version: '3.1'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: english
      MYSQL_DATABASE: english
      MYSQL_USER: english
      MYSQL_PASSWORD: english
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql

  app:
    build:
      context: ./docker/php-fpm
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /var/www/html
    user: ${UID}:${GID}

  webserver:
    image: nginx
    working_dir: /application
    depends_on:
      - app
    links:
      - app
    volumes:
      - ./public:/var/www/html/public
      - ./storage/logs/nginx/:/var/log/nginx
      - ./docker/nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
      - '443:443'

volumes:
  db:
